### Exemplo de configuração do SCST com 4 LUNs, uma placa QLogic e duas LUNs apresentadas com restrição de WWN


HANDLER vdisk_blockio {
        DEVICE lun01 {
                filename /dev/vg_stg/lun01
                size 10995116277760
        }

        DEVICE lun02 {
                filename /dev/vg_stg/lun02
                size 10995116277760
        }

        DEVICE lun03 {
                filename /dev/vg_stg/lun03
                size 5497558138880
        }

        DEVICE lun04 {
                filename /dev/vg_stg/lun04
                size 5497558138880
        }
}

TARGET_DRIVER copy_manager {
        TARGET copy_manager_tgt {
                LUN 0 lun01
                LUN 1 lun02
                LUN 2 lun03
                LUN 3 lun04
        }
}

TARGET_DRIVER qla2x00t {
        TARGET 21:00:00:1b:32:94:31:e3 {
                HW_TARGET

                enabled 1
                rel_tgt_id 1

                #LUN3 e 4 nao estao apresentadas para nenhum grupo
                LUN 3 lun03
                LUN 4 lun04

                GROUP HOST01_ONLY {
                        LUN 1 lun01

                        INITIATOR 21:00:00:24:ff:58:98:57
                }

                GROUP HOST02_ONLY {
                        LUN 2 lun02

                        INITIATOR 10:00:00:00:c9:99:6f:c3
                }
        }
}